---
title: "Lectura y analisis de datos"
output: html_notebook
---

Para leer un archivo excel, necesitamos el paquete readxl
```{r}
install.packages("readxl")
install.packages("Dict")
```

```{r}
library("readxl")
library("Dict")
library(dplyr)
library(DT)
library(stringi)
```

```{r}
rep_path <- "data/DATA-PRUEBA-REPITENCIAS 2017-2020-FISI.xlsx"
calf_path <- "data/DATA-PRUEBA_CALIFICACIONES  2017-2020-FISI.xlsx"
tuto_path <- "data/DATA-PRUEBA_TUTORIAS 2017-2020-FISI.xlsx"

rep_semesters <- excel_sheets(rep_path)
calf_semesters <- excel_sheets(calf_path)
tuto_semesters <- excel_sheets(tuto_path)

data.rep <- NULL
data.calf <- NULL
data.tuto <- NULL

# param: 
# sheetNameList

func_union <- function(sheet_name_list) {
  result <- NULL
  for(item in rep_semesters) {
    buffer <- read_excel("data/DATA-PRUEBA-REPITENCIAS 2017-2020-FISI.xlsx", 
                                        sheet=item)
    if(typeof(buffer$cod_semestre) == "double") {
      buffer$cod_semestre <- as.character(buffer$cod_semestre)
    }
    if(is.null(result)) {
      result <- buffer
    } else {
      result <- bind_rows(result, buffer)
    }
    rm(buffer)
  }  
  
  return (result)
}

data.rep <- func_union(rep_semesters)
data.calf <- func_union(calf_semesters)
data.tuto <- func_union(tuto_semesters)

data.rep$asignatura <- lapply(data.rep$asignatura,function(item) stri_trans_general(str=item, id="ASCII"))
data.calf$asignatura <- lapply(data.calf$asignatura,function(item) stri_trans_general(str=item, id="ASCII"))
data.tuto$asignatura <- lapply(data.tuto$asignatura,function(item) stri_trans_general(str=item, id="ASCII"))

saveRDS(data.rep,file="fisiRepData.rds")
saveRDS(data.calf,file="fisiCalfData.rds")
saveRDS(data.tuto,file="fisiTutoData.rds")

```

```{r}
data2 <- readRDS("fisiRepData.rds")
```

```{r}
print("===========data.rep==============")
print(colnames(data.rep))
print("=================================")
print("===========data.calf==============")
print(colnames(data.calf))
print("=================================")
print("===========data.tuto==============")
print(colnames(data.tuto))
print("=================================")
```

```{r}
library(stringi)
```

```{r}

data.rep$asignatura <- lapply(data.rep$asignatura,function(item) stri_trans_general(str=item, id="ASCII"))

test_data <- data.rep %>%
  filter(cod_semestre=="20171") %>%
  select(asignatura, num_rep) %>%
  group_by(asignatura) %>%
  summarise(num_rep = sum(num_rep)) %>%
  arrange(num_rep)

```

```{r}
library(plotly)
library(showtext)
## Loading Google fonts (https://fonts.google.com/)
showtext_auto()
font_add_google("Gochi Hand", "gochi")
```

```{r}
fig <- plot_ly(x=test_data$num_rep, y=test_data$asignatura,type='bar',orientation='h',sizes = c(10, 300))
fig <- fig %>% layout(autosize = F, width = 1000, height = 1000)
fig
```

